<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_Gender</name>
   <tag></tag>
   <elementGuidId>242d49cf-ec1a-4279-ac73-748a3c01669b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Nữ']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input.e-select__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>e-select__input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Nữ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;dark lang-vi&quot;]/div[@class=&quot;main-wrapper&quot;]/div[@class=&quot;settings&quot;]/section[@class=&quot;settings__body&quot;]/div[@class=&quot;settings__content&quot;]/form[@class=&quot;e-form account-settings__form&quot;]/div[@class=&quot;account-settings__row--flex&quot;]/div[@class=&quot;e-form-item account-settings__form-item&quot;]/div[@class=&quot;e-form-item account-settings__render-item&quot;]/div[@class=&quot;e-select&quot;]/div[@class=&quot;e-select__input-wrapper e-select__arrow--bottom&quot;]/input[@class=&quot;e-select__input&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Nữ']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/div/div/section/div[2]/form/div/div/div[2]/div/div/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/input</value>
   </webElementXpaths>
</WebElementEntity>
